### ISSUE TITLE
Scrollable custom link card component

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#103]
Create a scrollable custom link card component that allows users to scroll through a list of items, each representing a different link. Ensure that clicking on a card navigates to a specific URL or performs a designated function.

**Comment by HectorRivera1** [comment]
Developed a 'linkBox' component which allows users to input and store text-based links. The component displays the stored links in a visible box, enabling users to easily access them. When clicked, the links open in new tabs, enhancing user experience by facilitating seamless navigation.
