### ISSUE TITLE
Notifications Functionality

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#129]
Add a Nav-bar element which brings up a floating window which holds notifications of upcoming events or important actions that need to be taken. 

Look at documentation events to get an idea of the types of notifications to create.

**Comment by Gaby-Concepcion** [comment]
Integrated notification bell icon in the navbar that when clicked on expands a view of the new or pending notifications. These notifications  can be marked as seen or dismissed; the bell icon can be clicked again to minimize this view.
- Pending Firebase Integration

**Comment by Gaby-Concepcion** [comment]
Firebase integration completed.
