### ISSUE TITLE
Create Standardized Basic Components

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#13]
These basic components, should have proper props so that they can be utilized throughout the entire project and match the styling and colors established in the figma.

- [x] Create button component
- [x] Text input component
- [x] Card Component
- [x] Navbar

**Comment by KevinIbarra1** [comment]
Implemented Button Component, created Routes, and implemented Navbar component.

**Comment by KevinIbarra1** [comment]
Implemented a responsive NavBar on mobile and desktop,  implemented react-router, fixed navBar bug, and implemented the base of Calendar page.(13/February/2023)

**Comment by ChristianMorales25** [comment]
Implemented text input component and stylized it to match the color scheme established in the Figma.

![Screenshot 2024-02-17 131256](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem/assets/98779265/f521d9fb-8f1e-4c48-a906-c2c797d033f8)

**Comment by ChristianMorales25** [comment]
Implemented card component and stylized it to match the Figma color scheme and style. Added instructions in the code for customization of the card depending on how it will be utilized throughout the project.

For example:
- How to remove image
- How to remove button

![Screenshot 2024-02-17 131712](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem/assets/98779265/e80643b4-c49a-4cbf-9b00-6117ca61dcd9)
