### ISSUE TITLE
Suggestion algorithm

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#132]
This algorithm is possibly one of the most important features that make the project distinct and is scored as such.

Here you will be tasked with creating an algorithm that can be triggered by the student that suggests courses based on the other courses that you have taken relevant to your program, and corresponding requisites. 

It should take into consideration the course that most immediately gives you access to other courses and generate a table of what each course could potentially unlock for you.

Think of it as when you go to your academic advisor, this algorithm should provide very similar suggestions to those that advisors give you.

The interface for this algorithm should be placed in a separate page for it to have enough space to generate both the suggested courses, and a calendar view of how taking those courses would look like.

**Comment by DerekUnii** [comment]
Created a new Page, CourseSugg
Added Drop down to select available tables.
Added Curriculum data to DB
Suggested classes are highlighted with a Yellow Background
