### ISSUE TITLE
Make studentpage curriculum components work with DB data

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#135]
The end-to-end components of student page work well with the appropriate data stored in csv files. The next step in the right direction would be to make these components read a student's respective data from the database, and doing any necessary changes so the components work well with the database. This would require the database to already have a student with the necessary data.

**Comment by CarlosRodriguez260** [comment]
Made it so the end-to-end components of student page (those being the graphic schedule, the course table and the exam grade viewer) all work with data from firebase. The components dynamically change if data is changed or added, and the data shown is always linked to that of a specific student's. 

This was implemented in branch #139 .
