### ISSUE TITLE
Filter Conditions for Displaying Courses Completion Statuses: AcademicProgress Page

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#137]
AcademicProgress Section:

Implement the functionality to filter the uncompleted courses and completed, and correctly displayed on the page.

![Image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem/assets/93481778/6dbbee01-2600-4b66-bb68-95738bdcebc3)

**Comment by SamuelRUM** [comment]
I would like if you the completed courses display was more as a table view rather than this long list with huge spacing as its harder to read and find which courses are completed

**Comment by christian-j174** [comment]
![Image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem/assets/93481778/e2ede6a3-53c5-4960-bf67-e165dfa863d0)
