### ISSUE TITLE
Make graphic schedule component register different schedules of same class

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#139]
- [x] Fix small issue in graphic schedule component on student page that doesn't correctly display if one class has different meeting times throughout a week.
- [x] Fix bug in schedule table component on student page that was not displaying any data pertinent to a student's courses in a semester.

**Comment by CarlosRodriguez260** [comment]
Fix the problems found on the components that were mentioned in this issue.
