### ISSUE TITLE
[Lecture Topic Task] Feedback Petri Net

### ISSUE THREAD

**Issue by javier-rivera8** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#149]
Create a Petri net model to represent the process of students leaving feedback. The Petri net will illustrate the various states and transitions involved in the feedback process, including student input, feedback submission, and feedback reception by professors.

**Comment by SamuelRUM** [comment]
Provide more information on the petri net, what are you fixing?
