### ISSUE TITLE
View available courses

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#15]
- [x] Course List component to display the courses available
- [x] Course card component to display course info
- [x] Filter component to let the user filter courses based on a certain criteria (instructor, availability)
- [x] Searchbar component to let the user search based on keywords

**Comment by pedro-gracia04** [comment]
Working on the Filter Component

**Comment by christian-j174** [comment]
Working on Course card component to display course info

**Comment by pedro-gracia04** [comment]
Working on the Searchbar Component
