### ISSUE TITLE
[Lecture Topic Task] Rewrite Behaviors

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#165]
This task is concerned with rewriting the behaviors to better suit the created diagrams and attempt to bring more closure.

**Comment by christian-j174** [comment]
Fixed events and behaviors and described returned objects and other parameter classes.

**Comment by SamuelRUM** [comment]
This is said to be closed, but don't see the relevant work, I see some, but other things aren't well defined
