### ISSUE TITLE
Issue: Limited Sidebar Interaction

### ISSUE THREAD

**Issue by diegoperez16** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#17]
Currently, the sidebar can only be closed by directly clicking the hamburger icon. To enhance usability, I've implemented a solution that allows the sidebar to be closed by clicking anywhere outside the navbar or by selecting an item within the navbar.

**Comment by SamuelRUM** [comment]
Did you already implement the interaction in a branch? if so, link it here please.

**Comment by diegoperez16** [comment]
I did already implement it, it's implemented in this branch @uprm-inso4101-2023-2024-s2/student-enrollmentsystem@UIfix. I attached it to this issue.
