### ISSUE TITLE
Multiple Calendars for Course schedule setups

### ISSUE THREAD

**Issue by Gaby-Concepcion** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#2]
- [x] Make Calendar Page
- [x] Develop Calendar Component
- [x] Develop Course Search 
- [x] Develop event courses components so that users can see the courses in the calendar
- [x] Calendar editor component so users are able to edit the calendar (add courses, remove)

**Comment by KevinIbarra1** [comment]
Developed weekly view for calendar component

**Comment by HectorRivera1** [comment]
Developed alternative views (daily and monthly) for the calendar component.
