### ISSUE TITLE
Display Profile

### ISSUE THREAD

**Issue by ChristianMorales25** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#3]
- [x] Page Foundation
- [x] Stats like GPA, active student, admission year, major, etc.
- [x] Picture
- [x] Bio
- [x] Implement buttons that allow the user to attach a link.
- [x] Adjust any overlapping or design bugs present(differentiating fonts, spacing error between components, etc.).
- [x] Remove outlines that were added as a guide.

Page Overview (left side is important for now.)
![Image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem/assets/94196471/444ceaa3-a407-4c70-afad-7953d082d21a)

**Comment by CarlosRodriguez260** [comment]
Foundation of page is 100% complete, which includes:

- Designated spaces for working on the profile and curriculum sides of the page
- Navigational bar on top left with header on top (will be replaced with Kevin Ibarra's navbar later on)

**Comment by Xenir19** [comment]
Implemented  a bio following the figma previously establish.  A bio section for the students to add info, added buttons that stores links for socials also made a switch button to display the academic calendar.

**Comment by Brandell13** [comment]
I have successfully integrated the profile picture functionality, enabling users to upload a personalized profile photo. This feature seamlessly operates in both sections of the profile display. Additionally, essential details such as Name, Department, GPA, Total Remaining, and Total Credits have been meticulously incorporated, empowering you to furnish comprehensive and accurate information

**Comment by alejandrois22** [comment]
Changed format and fix some overlapping issues. Removed guide outlines. Fixed uneven fonts and minor design inconsistencies.
