### ISSUE TITLE
Curriculum Component

### ISSUE THREAD

**Issue by ChristianMorales25** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#4]
- [x] Setup view of the current courses that are being taken.
- [x] Ability to view previous semesters
- [x] View grades on the course taken

**Comment by ChristianMorales25** [comment]
Implemented grade view on the course table and the past semester table. This was done using dummy data for the time being.

**Comment by CarlosRodriguez260** [comment]
Implemented table that reads "csv" data containing students semester information, and displayed it on page.

**Comment by jeansantana4** [comment]
Implemented two buttons to be able to see past semesters. In the process a second table (coursetable2) was created to represent the past semester given.

**Comment by SamuelRUM** [comment]
Link the branch for the issue please
