### ISSUE TITLE
Calendar View of Professor office hours

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#41]
A view that displays all of the enrolled courses professor's office hours and potential conflicts with current classes the student is taking.

- [x] Manual Data Entry of Each professors office hours
- [x] Display Data on Calendars

**Comment by CarlosRodriguez260** [comment]
Implemented dummy data of professor office hours from a csv to be displayed in the student's schedule table. Created a button that lets the student display these office hours over class hours so they can check for possible collision's between schedules.
