### ISSUE TITLE
Schedule drafts functionality/page

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#43]
Allow for the user to make a variety of potential weekly schedules (3-5) in order to better plan out and weigh different class distributions and electives options.

**Comment by alejandrois22** [comment]
Here's a description of how I solved the issues:

Creation of New Schedule Drafts:
Implemented functionality to add new schedule drafts to the calendar. Users can now create multiple schedule drafts by clicking the "Add Schedule" button.
Each new schedule draft is appended to the existing list of schedules, with a default name ("Schedule [index]") and an empty list of events.

Removal of Schedule Drafts:
Integrated a feature to remove schedule drafts from the calendar. Users can delete schedule drafts by clicking the "Remove Schedule" button.
Removal of schedule drafts is handled gracefully, ensuring that at least one schedule draft remains in the calendar at all times.
