### ISSUE TITLE
Academic Progress Section

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#44]
This section should display the students curriculum/program and highlight courses taken, be it based on filters or simply completed/not completed.

**Comment by christian-j174** [comment]
**### Requirements:**
**Progress Bar:** Shows the remaining time to complete your program or bachelor's degree.
**Highlight Courses Taken**: Provides a list of courses already completed, alongside those yet to be taken.
**Filters/Conditions**: Offers the ability to sort and filter courses based on specific criteria or queries.

**Comment by christian-j174** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem/assets/93481778/e34e7a37-bae1-4b9a-a143-2830051ee5db)

Expected Visualization for this task

**Comment by christian-j174** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem/assets/93481778/622f112e-beb8-440a-b520-20e47324e09a)

as today march 15, i have this code, still needs to implement the styles

**Comment by christian-j174** [comment]
@SamuelRUM @Gaby-Concepcion any feedback?

**Comment by SamuelRUM** [comment]
looks awesome!
