### ISSUE TITLE
Course Reviews

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#47]
Students can leave reviews on a course and includes the professor they took it with so other students have reference to that information that could help them plan better.

**Comment by diegoperez16** [comment]
This feauture has been in progress for various weeks.

**Comment by diegoperez16** [comment]
> This feauture has been in progress for various weeks.
It was my fault, I never moved it to "in progress"

**Comment by diegoperez16** [comment]
Linked branch to the issue.
