### ISSUE TITLE
Centralize Free Elective Courses

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#49]
Create a page that contains a list of all free electives and socio-humanistic courses available in UPRM.

**Comment by ChristianMorales25** [comment]
Created the Free Elective page where all the currently offered electives and socio-humanistics courses are displayed in a table. All the courses were taken from the uprm websites and put together in a csv file for easier readability, then coded each course into the table that is present in the web page. Implemented a search bar for the user to search for a specific course. Also implemented a feature where the user can choose how many entries they want to be displayed on the page at once(the options are: 10, 25, 50 and 100). The table will automatically adjust it's size depending on number of entries. I have also added the page to the navbar and specified a link that directs to the page.
