### ISSUE TITLE
Counselor Information

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#51]
Implement counselor's information (name, e-mail, phone number) inside the student page.

**Comment by alejandrois22** [comment]
This is how I solved this issue:

Enhancements:
Counselor Information Display: Implemented the display of counselor contact details (name, email, phone) within the StudentCard in the Student Page. This allows students to access their counselor's contact information directly from their profile.

Implementation Details:
CounselorInfo Component: Utilized the CounselorInfo component within StudentCard to present the counselor's details in a structured manner.
Data Passing: Enhanced the StudentPage to include counselor information in its state and facilitated the passing of this information to the StudentCard as props (counselorName, counselorEmail, counselorPhone).

**Comment by SamuelRUM** [comment]
I like that you separated it into a component so that further on we can simply pass data to the component instead of making it editable. have some bonus points.
