### ISSUE TITLE
IMPORTANT: Create Milestones 1 & 2 on GitHub

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#66]

**Comment by Gaby-Concepcion** [comment]
Assigned all issues, closed or open, to their corresponding Milestone.

**Comment by Gaby-Concepcion** [comment]
Ran test metrics for Milestone #1 and they were produced without issue. 
>(Might require talking to TA or professor to validate the priority and difficulty values as it does not seem to recognize the teams tags)
