### ISSUE TITLE
Active Exam Grade Viewer

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#68]
In accordance to the current classes a student is taking, they would be able to see what grades they have gotten on exams that they have taken throughout a semester.

**Comment by CarlosRodriguez260** [comment]
Implemented a table component on student page, below the course and schedule table, which allows the student to see the grades he has gotten on exams he has taken throughout his current/active semester. Data of the exams student has taken comes from dummy data in csv files.
